version: '3'

services:

  ## MySQL Docker compose config
  mysql-estudou:
    container_name: mysql-estudou
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=estudou_db
      - MYSQL_USER=jeiel
      - MYSQL_PASSWORD=jeiel
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-estudou:/var/lib/mysql

  ## Mongo configuration
  mongo-estudou:
    container_name: mongo-estudou
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db

  ## Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=jeiel
      - DB_PASSWORD=jeiel
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - mysql-keycloak

  ## Keycloak configuration
  mysql-keycloak:
    container_name: mysql-keycloak
    image: mysql
    volumes:
      - ./mysql-keycloak:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=jeiel
      - MYSQL_PASSWORD=jeiel
      - MYSQL_ROOT_PASSWORD=password

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=1000

  ## KAFKA Broker
  broker:
    image: confluentinc/cp-kafka:7.5.3
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1