version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.4
      container_name: keycloak
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
        - "8181:8080"
      restart: always
      volumes:
        - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
      command: ["start-dev"]